name = "sample"
version = "1"

# optional, but apk is the default.
install = "apk add"
update = "apk update"

packages = [
  "biber", "python3"
]

[inherit]
docker = "alpine"

[files]
"helloworld.sh" = "/helloworld.sh"

[project.files]
"main.tex" = "main.tex"
"Makefile" = "Makefile"

[project.commands]
compile = "latexmk -pdf main.tex"
watch = "latexmk -pdf -pvc main.tex"
clean = "rm -rf main.aux main.log"
